### ISSUE TITLE
Diff guidelines against ICMJE guidelines

### ISSUE THREAD

**Issue by sdruskat** [sdruskat/software-authorship#17]
https://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html

**Comment by GemmaTuron** [comment]
I am adding here some reflections on the ICMJE guidelines in #5 
(+)

Good paragraph on why authorship matters --> probably we should kind of have an statement of why authorship in software matters?
Includes what it means to be an author: accountability for scientific research is translatable to accountability for OS software?
Clear guideline: if you do not meet the 4 criteria, you are not considered an author
(-)

Very narrow definition of what an author is, rest are simply "acknowledged" - probably for OSS we want a more broad definition

**Comment by sdruskat** [comment]
Done with https://github.com/sdruskat/software-authorship/commit/166c7c8b22142259dbe18aef5ac373ea1e2ee90a.
