### ISSUE TITLE
Authorship definitions for scientific publications 

### ISSUE THREAD

**Issue by GemmaTuron** [sdruskat/software-authorship#2]
It would be useful to check the authorship definition for scientific publications and identify which pieces are appropriate for research software and which ones are not

**Comment by sdruskat** [comment]
- Potential starting point: https://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html

**Comment by GemmaTuron** [comment]
Also the CRediT system: [](https://www.elsevier.com/authors/policies-and-guidelines/credit-author-statement)
