### ISSUE TITLE
Transfer first draft to collaborative form

### ISSUE THREAD

**Issue by sdruskat** [sdruskat/software-authorship#43]
Transfer the draft of the software authorship definition to a collaborative form to allow better commenting and collaboration.

Suggested: Google Doc

**Comment by GemmaTuron** [comment]
I've created this [file](https://docs.google.com/document/d/1z4YuS4A9WQn56BJ6DQx5EASqkf_sXFMRt3zjJPUrwec/) for collaboration in a GDocs as suggested.
I have not included the taxonomy in it as I was unsure if we would have everything in the same place

**Comment by sdruskat** [comment]
Thanks @GemmaTuron, copied into the Google Drive for the Task Force.
We can do the work of preparing the document for comments, etc., within the Task Force.
